name: Build and Push Recorder Image

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'recorder/**'
      - '.github/workflows/deploy-recorder.yml'

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      PREFIX: ${{ github.ref == 'refs/heads/main' && 'PROD' || 'STAGING' }}
      DOCKER_TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || 'staging' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets[format('{0}_GCP_SA_KEY', env.PREFIX)] }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        env:
          GCP_PROJECT_ID: ${{ secrets[format('{0}_GCP_PROJECT_ID', env.PREFIX)] }}
          IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets[format('{0}_GCP_PROJECT_ID', env.PREFIX)] }}/vjplay-repo/recorder
        run: |
          cd recorder
          docker build -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:${{ env.DOCKER_TAG }} .
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:${{ env.DOCKER_TAG }}
